### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by billy1234567892** [Comrogue/RobloxGroupAdmin#1]
Can you set it up please for http://www.roblox.com/My/Groups.aspx?gid=1233529

ftp  info
You're hosted on eu5.org 
server. Account Manager is 
located at http://eu5org.freewebhostingarea.com/.

Username: 

robloxgroupadmin.eu5.org

Password: password
If you have accounts created on more than one server, see
http://www.freewebhostingarea.com/members/.
 
Some scripts require server path. Yours is 

/home/vhosts/robloxgroupadmin.eu5.org.

Your Personal FTP Information:

FTP Server/Host:

eu5.org

FTP Login/Username:

robloxgroupadmin.eu5.org

FTP PassWord:

password

**Comment by billy1234567892** [comment]
RobloxGroupAdmin Please

**Comment by Comrogue** [comment]
Your site is set up now.
